// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Documentation
{
    internal sealed partial class Vsix
    {
        public const string Id = "Documentation.f8dbd448-aec8-4629-a288-d037ae1bee3e";
        public const string Name = "Documentation";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Bank Millennium S.A.";
        public const string Tags = "";
    }
}
